/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DimensionLine struct {
	// The parentId property for the Dynamics 365 Business Central dimensionLine entity
	ParentId string `json:"parentId,omitempty"`
	// The id property for the Dynamics 365 Business Central dimensionLine entity
	Id string `json:"id,omitempty"`
	// The code property for the Dynamics 365 Business Central dimensionLine entity
	Code string `json:"code,omitempty"`
	// The displayName property for the Dynamics 365 Business Central dimensionLine entity
	DisplayName string `json:"displayName,omitempty"`
	// The valueId property for the Dynamics 365 Business Central dimensionLine entity
	ValueId string `json:"valueId,omitempty"`
	// The valueCode property for the Dynamics 365 Business Central dimensionLine entity
	ValueCode string `json:"valueCode,omitempty"`
	// The valueDisplayName property for the Dynamics 365 Business Central dimensionLine entity
	ValueDisplayName string     `json:"valueDisplayName,omitempty"`
	Dimension        *Dimension `json:"dimension,omitempty"`
}
