/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Company struct {
	Accounts               []Account                `json:"accounts,omitempty"`
	AgedAccountsPayable    []AgedAccountsPayable    `json:"agedAccountsPayable,omitempty"`
	AgedAccountsReceivable []AgedAccountsReceivable `json:"agedAccountsReceivable,omitempty"`
	Attachments            []Attachments            `json:"attachments,omitempty"`
	BalanceSheet           []BalanceSheet           `json:"balanceSheet,omitempty"`
	BankAccounts           []BankAccount            `json:"bankAccounts,omitempty"`
	// The businessProfileId property for the Dynamics 365 Business Central company entity
	BusinessProfileId        string                    `json:"businessProfileId,omitempty"`
	CashFlowStatement        []CashFlowStatement       `json:"cashFlowStatement,omitempty"`
	CompanyInformation       []CompanyInformation      `json:"companyInformation,omitempty"`
	CountriesRegions         []CountryRegion           `json:"countriesRegions,omitempty"`
	Currencies               []Currency                `json:"currencies,omitempty"`
	CustomerFinancialDetails []CustomerFinancialDetail `json:"customerFinancialDetails,omitempty"`
	CustomerPaymentJournals  []CustomerPaymentJournal  `json:"customerPaymentJournals,omitempty"`
	CustomerPayments         []CustomerPayment         `json:"customerPayments,omitempty"`
	CustomerSales            []CustomerSale            `json:"customerSales,omitempty"`
	Customers                []Customer                `json:"customers,omitempty"`
	DefaultDimensions        []DefaultDimensions       `json:"defaultDimensions,omitempty"`
	DimensionLines           []DimensionLine           `json:"dimensionLines,omitempty"`
	DimensionValues          []DimensionValue          `json:"dimensionValues,omitempty"`
	Dimensions               []Dimension               `json:"dimensions,omitempty"`
	// The displayName property for the Dynamics 365 Business Central company entity
	DisplayName                   string                          `json:"displayName,omitempty"`
	Employees                     []Employee                      `json:"employees,omitempty"`
	GeneralLedgerEntries          []GeneralLedgerEntry            `json:"generalLedgerEntries,omitempty"`
	GeneralLedgerEntryAttachments []GeneralLedgerEntryAttachments `json:"generalLedgerEntryAttachments,omitempty"`
	// The id property for the Dynamics 365 Business Central company entity
	Id              string            `json:"id,omitempty"`
	IncomeStatement []IncomeStatement `json:"incomeStatement,omitempty"`
	ItemCategories  []ItemCategory    `json:"itemCategories,omitempty"`
	Items           []Item            `json:"items,omitempty"`
	JournalLines    []JournalLine     `json:"journalLines,omitempty"`
	Journals        []Journal         `json:"journals,omitempty"`
	// The name property for the Dynamics 365 Business Central company entity
	Name                      string                      `json:"name,omitempty"`
	PaymentMethods            []PaymentMethod             `json:"paymentMethods,omitempty"`
	PaymentTerms              []PaymentTerm               `json:"paymentTerms,omitempty"`
	PdfDocument               []PdfDocument               `json:"pdfDocument,omitempty"`
	Picture                   []Picture                   `json:"picture,omitempty"`
	Projects                  []Project                   `json:"projects,omitempty"`
	PurchaseInvoiceLines      []PurchaseInvoiceLine       `json:"purchaseInvoiceLines,omitempty"`
	PurchaseInvoices          []PurchaseInvoice           `json:"purchaseInvoices,omitempty"`
	RetainedEarningsStatement []RetainedEarningsStatement `json:"retainedEarningsStatement,omitempty"`
	SalesCreditMemoLines      []SalesCreditMemoLine       `json:"salesCreditMemoLines,omitempty"`
	SalesCreditMemos          []SalesCreditMemo           `json:"salesCreditMemos,omitempty"`
	SalesInvoiceLines         []SalesInvoiceLine          `json:"salesInvoiceLines,omitempty"`
	SalesInvoices             []SalesInvoice              `json:"salesInvoices,omitempty"`
	SalesOrderLines           []SalesOrderLine            `json:"salesOrderLines,omitempty"`
	SalesOrders               []SalesOrder                `json:"salesOrders,omitempty"`
	SalesQuoteLines           []SalesQuoteLine            `json:"salesQuoteLines,omitempty"`
	SalesQuotes               []SalesQuote                `json:"salesQuotes,omitempty"`
	ShipmentMethods           []ShipmentMethod            `json:"shipmentMethods,omitempty"`
	// The systemVersion property for the Dynamics 365 Business Central company entity
	SystemVersion           string                  `json:"systemVersion,omitempty"`
	TaxAreas                []TaxArea               `json:"taxAreas,omitempty"`
	TaxGroups               []TaxGroup              `json:"taxGroups,omitempty"`
	TimeRegistrationEntries []TimeRegistrationEntry `json:"timeRegistrationEntries,omitempty"`
	TrialBalance            []TrialBalance          `json:"trialBalance,omitempty"`
	UnitsOfMeasure          []UnitOfMeasure         `json:"unitsOfMeasure,omitempty"`
	VendorPurchases         []VendorPurchase        `json:"vendorPurchases,omitempty"`
	Vendors                 []Vendor                `json:"vendors,omitempty"`
}
