/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DefaultDimensions struct {
	// The parentId property for the Dynamics 365 Business Central defaultDimensions entity
	ParentId string `json:"parentId,omitempty"`
	// The dimensionId property for the Dynamics 365 Business Central defaultDimensions entity
	DimensionId string `json:"dimensionId,omitempty"`
	// The dimensionCode property for the Dynamics 365 Business Central defaultDimensions entity
	DimensionCode string `json:"dimensionCode,omitempty"`
	// The dimensionValueId property for the Dynamics 365 Business Central defaultDimensions entity
	DimensionValueId string `json:"dimensionValueId,omitempty"`
	// The dimensionValueCode property for the Dynamics 365 Business Central defaultDimensions entity
	DimensionValueCode string `json:"dimensionValueCode,omitempty"`
	// The postingValidation property for the Dynamics 365 Business Central defaultDimensions entity
	PostingValidation string          `json:"postingValidation,omitempty"`
	Account           *Account        `json:"account,omitempty"`
	Dimension         *Dimension      `json:"dimension,omitempty"`
	DimensionValue    *DimensionValue `json:"dimensionValue,omitempty"`
}
