/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Dimension struct {
	// The code property for the Dynamics 365 Business Central dimension entity
	Code            string           `json:"code,omitempty"`
	DimensionValues []DimensionValue `json:"dimensionValues,omitempty"`
	// The displayName property for the Dynamics 365 Business Central dimension entity
	DisplayName string `json:"displayName,omitempty"`
	// The id property for the Dynamics 365 Business Central dimension entity
	Id string `json:"id,omitempty"`
	// The lastModifiedDateTime property for the Dynamics 365 Business Central dimension entity
	LastModifiedDateTime time.Time `json:"lastModifiedDateTime,omitempty"`
}
