/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Postaladdresstype struct {
	// The city property for the Dynamics 365 Business Central postaladdresstype entity
	City string `json:"city,omitempty"`
	// The countryLetterCode property for the Dynamics 365 Business Central postaladdresstype entity
	CountryLetterCode string `json:"countryLetterCode,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	CustomerFinancialDetails []CustomerFinancialDetail `json:"customerFinancialDetails,omitempty"`
	DefaultDimensions []DefaultDimensions `json:"defaultDimensions,omitempty"`
	PaymentMethod *PaymentMethod `json:"paymentMethod,omitempty"`
	PaymentTerm *PaymentTerm `json:"paymentTerm,omitempty"`
	Picture []Picture `json:"picture,omitempty"`
	// The postalCode property for the Dynamics 365 Business Central postaladdresstype entity
	PostalCode string `json:"postalCode,omitempty"`
	ShipmentMethod *ShipmentMethod `json:"shipmentMethod,omitempty"`
	// The state property for the Dynamics 365 Business Central postaladdresstype entity
	State string `json:"state,omitempty"`
	// The street property for the Dynamics 365 Business Central postaladdresstype entity
	Street string `json:"street,omitempty"`
}
