/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Employee struct {
	Address *Postaladdresstype `json:"address,omitempty"`
	// The birthDate property for the Dynamics 365 Business Central employee entity
	BirthDate string `json:"birthDate,omitempty"`
	DefaultDimensions []DefaultDimensions `json:"defaultDimensions,omitempty"`
	// The displayName property for the Dynamics 365 Business Central employee entity
	DisplayName string `json:"displayName,omitempty"`
	// The email property for the Dynamics 365 Business Central employee entity
	Email string `json:"email,omitempty"`
	// The employmentDate property for the Dynamics 365 Business Central employee entity
	EmploymentDate string `json:"employmentDate,omitempty"`
	// The givenName property for the Dynamics 365 Business Central employee entity
	GivenName string `json:"givenName,omitempty"`
	// The id property for the Dynamics 365 Business Central employee entity
	Id string `json:"id,omitempty"`
	// The jobTitle property for the Dynamics 365 Business Central employee entity
	JobTitle string `json:"jobTitle,omitempty"`
	// The lastModifiedDateTime property for the Dynamics 365 Business Central employee entity
	LastModifiedDateTime time.Time `json:"lastModifiedDateTime,omitempty"`
	// The middleName property for the Dynamics 365 Business Central employee entity
	MiddleName string `json:"middleName,omitempty"`
	// The mobilePhone property for the Dynamics 365 Business Central employee entity
	MobilePhone string `json:"mobilePhone,omitempty"`
	// The number property for the Dynamics 365 Business Central employee entity
	Number string `json:"number,omitempty"`
	// The personalEmail property for the Dynamics 365 Business Central employee entity
	PersonalEmail string `json:"personalEmail,omitempty"`
	// The phoneNumber property for the Dynamics 365 Business Central employee entity
	PhoneNumber string `json:"phoneNumber,omitempty"`
	Picture []Picture `json:"picture,omitempty"`
	// The statisticsGroupCode property for the Dynamics 365 Business Central employee entity
	StatisticsGroupCode string `json:"statisticsGroupCode,omitempty"`
	// The status property for the Dynamics 365 Business Central employee entity
	Status string `json:"status,omitempty"`
	// The surname property for the Dynamics 365 Business Central employee entity
	Surname string `json:"surname,omitempty"`
	// The terminationDate property for the Dynamics 365 Business Central employee entity
	TerminationDate string `json:"terminationDate,omitempty"`
	TimeRegistrationEntries []TimeRegistrationEntry `json:"timeRegistrationEntries,omitempty"`
}
