/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// PaymentMethod struct for PaymentMethod
type PaymentMethod struct {
	// The id property for the Dynamics 365 Business Central paymentMethod entity
	Id string `json:"id,omitempty"`
	// The code property for the Dynamics 365 Business Central paymentMethod entity
	Code string `json:"code,omitempty"`
	// The displayName property for the Dynamics 365 Business Central paymentMethod entity
	DisplayName *string `json:"displayName,omitempty"`
	// The lastModifiedDateTime property for the Dynamics 365 Business Central paymentMethod entity
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
}
