/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20026 struct for InlineResponse20026
type InlineResponse20026 struct {
	Value []PaymentTerm `json:"value,omitempty"`
}
