/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20033 struct for InlineResponse20033
type InlineResponse20033 struct {
	Value []RetainedEarningsStatement `json:"value,omitempty"`
}
