/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20028 struct for InlineResponse20028
type InlineResponse20028 struct {
	Value []ItemCategory `json:"value,omitempty"`
}
