/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20012 struct for InlineResponse20012
type InlineResponse20012 struct {
	Value []CustomerPayment `json:"value,omitempty"`
}
