/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// IncomeStatement struct for IncomeStatement
type IncomeStatement struct {
	// The lineNumber property for the Dynamics 365 Business Central incomeStatement entity
	LineNumber int32 `json:"lineNumber,omitempty"`
	// The display property for the Dynamics 365 Business Central incomeStatement entity
	Display *string `json:"display,omitempty"`
	// The netChange property for the Dynamics 365 Business Central incomeStatement entity
	NetChange *float32 `json:"netChange,omitempty"`
	// The lineType property for the Dynamics 365 Business Central incomeStatement entity
	LineType *string `json:"lineType,omitempty"`
	// The indentation property for the Dynamics 365 Business Central incomeStatement entity
	Indentation *int32 `json:"indentation,omitempty"`
	// The dateFilter property for the Dynamics 365 Business Central incomeStatement entity
	DateFilter *time.Time `json:"dateFilter,omitempty"`
}
