/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Value []Item `json:"value,omitempty"`
}
