/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse2004 struct for InlineResponse2004
type InlineResponse2004 struct {
	Value []Customer `json:"value,omitempty"`
}
