/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20023 struct for InlineResponse20023
type InlineResponse20023 struct {
	Value []Dimension `json:"value,omitempty"`
}
