/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20041 struct for InlineResponse20041
type InlineResponse20041 struct {
	Value []SalesQuote `json:"value,omitempty"`
}
