/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse2005 struct for InlineResponse2005
type InlineResponse2005 struct {
	Value []CustomerFinancialDetail `json:"value,omitempty"`
}
