/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Value []Company `json:"value,omitempty"`
}
