/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20039 struct for InlineResponse20039
type InlineResponse20039 struct {
	Value []IncomeStatement `json:"value,omitempty"`
}
