/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse2009 struct for InlineResponse2009
type InlineResponse2009 struct {
	Value []SalesInvoiceLine `json:"value,omitempty"`
}
